### PR TITLE
CI integration

### PR DESCRIPTION
**Pull request by bgruening**
First try to get CI working.

### CODE REVIEW

**Comment by erasche** [comment]
Giving up for now @bgruening 

```
|  debuggroup summary 7.82s processing track_2 scatter circos/conf/../data/data-2.txt

|  debuggroup summary 7.97s drawing track_0 histogram z 0 data-0.txt orient out

|  debuggroup summary 8.00s found conf file /tmp/tmpwZsDdP/job_working_directory/000/5/conda-env/bin/../etc/tracks/axis.conf

|  debuggroup summary 8.91s drawing track_1 tile z 0 data-1.txt orient out

|  debuggroup summary 8.92s found conf file /tmp/tmpwZsDdP/job_working_directory/000/5/conda-env/bin/../etc/tracks/axis.conf

|  WARNING *** Data point of type [tile] [3013-6130] extended past end of ideogram [ctgB 0-6079]. This data point will be [trimmed].

|  debuggroup summary 9.19s drawing track_2 scatter z 0 data-2.txt orient out

|  debuggroup summary 9.22s found conf file /tmp/tmpwZsDdP/job_working_directory/000/5/conda-env/bin/../etc/tracks/axis.conf

|  debuggroup output 9.50s generating output

|  debuggroup output 10.56s created PNG image ./circos.png (654 kb)

|  debuggroup output 10.56s created SVG image ./circos.svg (381 kb)

| Dataset Job Standard Error:

|  Fatal error: Exit code 1 ()

|  INFO:root:Processing /tmp/tmpwZsDdP/files/000/dataset_2.dat.wig

|  INFO:root:Processing /tmp/tmpwZsDdP/files/000/dataset_3.dat.gff3

|  INFO:root:Processing /tmp/tmpwZsDdP/files/000/dataset_4.dat.wig

|  Use of uninitialized value in join or string at /tmp/tmpwZsDdP/job_working_directory/000/5/conda-env/bin/../lib/Circos/Heatmap.pm line 75.

|  Use of uninitialized value in join or string at /tmp/tmpwZsDdP/job_working_directory/000/5/conda-env/bin/../lib/Circos/Heatmap.pm line 75.

|  Use of uninitialized value in join or string at /tmp/tmpwZsDdP/job_working_directory/000/5/conda-env/bin/../lib/Circos/Heatmap.pm line 75.

|  mv: cannot stat `circos/circos.png': No such file or directory
```

Note the `created PNG image ./circos.png (654 kb)` followed by `circos/circos.png`

**Comment by erasche** [comment]
Will come back to this later today/tomorrow AM.

**Comment by bgruening** [comment]
Fixed and merge! :)

**Comment by erasche** [comment]
I suppose that works :P

**Comment by bgruening** [comment]
Hope this merge was ok, I'm excited ....

**Comment by erasche** [comment]
Definitely!!!

**Pull request merged**
